# Generated by Django 3.0.3 on 2020-02-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title ', max_length=120)),
                ('content', models.TextField(default='Content ')),
                ('author', models.CharField(default='Author name', max_length=120)),
                ('date', models.DateField()),
            ],
        ),
    ]
