# Generated by Django 3.0.3 on 2020-02-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Product Title ', max_length=120)),
                ('description', models.TextField(default='Product Description')),
                ('price', models.CharField(default='00.00', max_length=120)),
            ],
        ),
    ]
