# Generated by Django 3.0.3 on 2020-02-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_shopproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='img',
            field=models.ImageField(default='true', upload_to='images/'),
        ),
    ]
